#!/usr/bin/env python
#
# Software License Agreement (BSD)
#
# @author    Mike Purvis <mpurvis@clearpathrobotics.com>
# @copyright (c) 2014, Clearpath Robotics, Inc., All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that
# the following conditions are met:
# * Redistributions of source code must retain the above copyright notice, this list of conditions and the
#   following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
#   following disclaimer in the documentation and/or other materials provided with the distribution.
# * Neither the name of Clearpath Robotics nor the names of its contributors may be used to endorse or
#   promote products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

import cStringIO
import cookielib
import glob
import logging
import os
import shutil
import subprocess
import sys
import tarfile
import urllib
import urllib2

logging.basicConfig(level=logging.INFO)
print('Starting python script------------------------------')
LOGIN_URL = 'https://www.ptgrey.com/login'
LOGIN_DATA = {
    'Email': 'code@clearpathrobotics.com',
    'Password': 'uNjRxoH6NMsJvi6hyPCH'
}

ARCHS = {
    'x86_64': (
        'https://www.ptgrey.com/support/downloads/11131/',
        'LaydbugSDK_1.16.3.48_amd64',
        'libladybug.so.1.16.3.48'),
}
archive_url, folder_name, shared_library = ARCHS[sys.argv[1]]
destination_folder = sys.argv[2]

print('Destination folder = ' + destination_folder)

if not os.path.exists(os.path.join(os.getcwd(), "usr/lib/")):
    if not os.path.exists(os.path.join(os.getcwd(), folder_name)):
        logging.info("Dummy")
        logging.info("Logging into ptgrey.com.")
        cj = cookielib.CookieJar()
        opener = urllib2.build_opener(urllib2.HTTPCookieProcessor(cj))
        opener.addheaders = [
            ('User-agent', 'Mozilla/5.0'),
            ('Referer', 'https://www.ptgrey.com')]
        opener.open(LOGIN_URL, urllib.urlencode(LOGIN_DATA))

        logging.info("Downloading SDK archive.")
        resp = opener.open(archive_url)

        logging.info("Unpacking tarball.")
        with tarfile.open(mode="r:", fileobj=cStringIO.StringIO(resp.read())) as tar:
            tar.extractall()

    logging.info("Unpacking debs.")

    debs = glob.glob(os.path.join(os.getcwd(), "ladybug-1.16.3.48_amd64.deb"))
    for deb in debs:
        subprocess.call(['dpkg', '-x', deb, os.path.join(os.getcwd(), folder_name)])
        logging.info("Deb: " + deb)
        logging.info("Deb in debs: Current working directory + folder = " + os.path.join(os.getcwd(), folder_name))

    logging.info("Current working dir = " + os.getcwd())
    if not os.path.exists(os.path.join(os.getcwd(), "usr")):
        os.mkdir(os.path.join(os.getcwd(), "usr"))
        logging.info("Making folder at : " + os.path.join(os.getcwd(), "usr"))

    # For every folder/file, copy it into the /usr folder we just created.
    logging.info("Copy directory = " + os.path.join(os.getcwd(), folder_name))
    for filename in os.listdir(os.path.join(os.getcwd(), folder_name, "usr")):
        logging.info("Copying file.")
        if not os.path.exists(os.path.join(os.getcwd(), "usr", filename)):
            shutil.move(os.path.join(os.getcwd(), folder_name, "usr", filename),
                        os.path.join(os.getcwd(), "usr", filename))

    logging.info("Finished with files.")
    # now we do some thing for XML files; copy them next to the catkin binary
    xml_path = os.path.join(os.getcwd(), "usr/lib/")
    xml_files = os.listdir(xml_path)

    try:
        os.makedirs(destination_folder)
    except:
        logging.info("Error XML folder either exists or can't be created.")

    for files in xml_files:
        if files.endswith(".xml"):
            origin_file = os.path.join(xml_path, files)
            print('Copying ' + origin_file + ' to ' + destination_folder)
            shutil.copy(origin_file, destination_folder)
